version: '3.8'
services: 
  mariadb:
    image: mariadb:10.5
    container_name: my_mariadb
    environment: 
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: egovdb
      MARIADB_USER: egovuser
      MARIADB_PASSWORD: egovpassword
    ports: 
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes: 
  mariadb_data: